version: '3.8'
services:
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - db
    restart: always
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    networks:
      - app-network
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eKurator
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - app-network
volumes:
  db_data:
networks:
  app-network:
    driver: bridge