version: '3.8'
services:
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - db
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    networks:
      - app-network
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eKurator
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
volumes:
  db_data:
networks:
  app-network:
    driver: bridge